### ISSUE TITLE
Why is ed25519 not supported?

### ISSUE THREAD

**Issue by 99linesofcode** [Mic92/ssh-to-pgp#83]
Hi,

GnuPGP has had support for ed25519 since version `2.1.0`. Is there a specific reason this tool does not support generating ed25519 keys instead of RSA?

Thanks!

**Comment by Mic92** [comment]
Because age is the recommendation for ed25519 keys.
I don't want to maintain more gnupg than necessary.
It's very complex and hard to use software.
